apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mi-app-route
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: myapp-prod-ingress.eastus2.cloudapp.azure.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ml-api-svc           # ← apunta al Service `ml-api-svc`
                port:
                  number: 8000               # ← puerto de tu Service
